# Generated by Django 4.2.7 on 2025-09-22 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدائرة')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الدائرة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدائرة')),
            ],
            options={
                'verbose_name': 'دائرة انتخابية',
                'verbose_name_plural': 'الدوائر الانتخابية',
                'ordering': ['governorate', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المحافظة')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد السكان')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='المساحة (كم²)')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الحزب')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='الاختصار')),
                ('logo', models.ImageField(blank=True, upload_to='parties/logos/', verbose_name='شعار الحزب')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='لون الحزب')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التأسيس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الحزب')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
            ],
            options={
                'verbose_name': 'حزب سياسي',
                'verbose_name_plural': 'الأحزاب السياسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='الرابط')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='المهنة')),
                ('education', models.TextField(blank=True, verbose_name='المؤهلات العلمية')),
                ('status', models.CharField(choices=[('candidate', 'مرشح'), ('elected', 'منتخب'), ('former', 'سابق')], default='candidate', max_length=20, verbose_name='الحالة')),
                ('electoral_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الانتخابي')),
                ('electoral_symbol', models.CharField(blank=True, max_length=255, verbose_name='الرمز الانتخابي')),
                ('election_year', models.PositiveIntegerField(default=2024, verbose_name='سنة الانتخاب')),
                ('profile_image', models.ImageField(blank=True, upload_to='representatives/profiles/', verbose_name='الصورة الشخصية')),
                ('banner_image', models.ImageField(blank=True, upload_to='representatives/banners/', verbose_name='صورة البانر')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='عدد المقيمين')),
                ('solved_complaints', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المحلولة')),
                ('received_complaints', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المستلمة')),
                ('is_distinguished', models.BooleanField(default=False, verbose_name='مرشح مميز')),
                ('bio', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('achievements', models.TextField(blank=True, verbose_name='الإنجازات')),
                ('electoral_program', models.TextField(blank=True, verbose_name='البرنامج الانتخابي')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الشخصي')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='content.district', verbose_name='الدائرة الانتخابية')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='content.politicalparty', verbose_name='الحزب')),
            ],
            options={
                'verbose_name': 'نائب/مرشح',
                'verbose_name_plural': 'النواب والمرشحين',
                'ordering': ['-is_distinguished', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('image', models.ImageField(upload_to='representatives/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='content.representative', verbose_name='النائب/المرشح')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': 'الصور الإضافية',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='صورة الخبر')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خبر مميز')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='content.representative', verbose_name='النائب/المرشح')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='content.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإنجاز')),
                ('description', models.TextField(verbose_name='وصف الإنجاز')),
                ('date', models.DateField(verbose_name='تاريخ الإنجاز')),
                ('image', models.ImageField(blank=True, upload_to='achievements/', verbose_name='صورة الإنجاز')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_list', to='content.representative', verbose_name='النائب/المرشح')),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'الإنجازات',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['slug'], name='content_rep_slug_ee71e4_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['district', 'party'], name='content_rep_distric_d04afa_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['status', 'is_distinguished'], name='content_rep_status_bd9d32_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['rating'], name='content_rep_rating_b65b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('governorate', 'number')},
        ),
    ]
