# Generated by Django 4.2.7 on 2025-09-22 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('color_type', models.CharField(choices=[('primary_green', 'الأخضر الأساسي'), ('primary_orange', 'البرتقالي الأساسي'), ('secondary_green', 'الأخضر الثانوي'), ('secondary_orange', 'البرتقالي الثانوي'), ('header_green', 'أخضر الهيدر'), ('footer_green', 'أخضر الفوتر'), ('news_ticker_orange', 'برتقالي الشريط الإخباري')], max_length=30, unique=True, verbose_name='نوع اللون')),
                ('color_value', models.CharField(max_length=7, verbose_name='قيمة اللون (HEX)')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='وصف الاستخدام')),
            ],
            options={
                'verbose_name': 'إعداد لون',
                'verbose_name_plural': 'إعدادات الألوان',
                'ordering': ['color_type'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('site_name', models.CharField(default='نائبك.كوم', max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف التواصل')),
                ('contact_address', models.TextField(blank=True, verbose_name='عنوان التواصل')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط إنستجرام')),
                ('youtube_url', models.URLField(blank=True, verbose_name='رابط يوتيوب')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
                ('visitor_counter_min', models.PositiveIntegerField(default=1000, verbose_name='الحد الأدنى لعداد الزوار')),
                ('visitor_counter_max', models.PositiveIntegerField(default=1500, verbose_name='الحد الأقصى لعداد الزوار')),
                ('logo_green', models.ImageField(blank=True, upload_to='logos/', verbose_name='اللوجو الأخضر')),
                ('logo_white', models.ImageField(blank=True, upload_to='logos/', verbose_name='اللوجو الأبيض')),
                ('favicon', models.ImageField(blank=True, upload_to='logos/', verbose_name='الفيف أيكون')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('page_type', models.CharField(choices=[('contact', 'اتصل بنا'), ('about', 'من نحن'), ('privacy', 'سياسات الخصوصية'), ('terms', 'اشتراطات واتفاقيات'), ('faq', 'أسئلة وأجوبة')], max_length=20, unique=True, verbose_name='نوع الصفحة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفحة')),
                ('content', models.TextField(verbose_name='محتوى الصفحة')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
                'ordering': ['order', 'page_type'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المناسبة')),
                ('description', models.TextField(verbose_name='وصف المناسبة')),
                ('event_type', models.CharField(choices=[('conference', 'مؤتمر'), ('meeting', 'اجتماع'), ('ceremony', 'حفل'), ('workshop', 'ورشة عمل'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المناسبة')),
                ('event_date', models.DateTimeField(verbose_name='تاريخ المناسبة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='المكان')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='صورة المناسبة')),
                ('admin_approved', models.BooleanField(default=False, verbose_name='موافقة الإدارة')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.representative', verbose_name='النائب')),
            ],
            options={
                'verbose_name': 'مناسبة',
                'verbose_name_plural': 'المناسبات والمؤتمرات',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البنر')),
                ('banner_type', models.CharField(choices=[('main', 'البنر الرئيسي'), ('representative', 'بنر النائب')], max_length=20, verbose_name='نوع البنر')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='صورة البنر')),
                ('is_default', models.BooleanField(default=False, verbose_name='البنر الافتراضي')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='content.representative', verbose_name='النائب')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'البنرات',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
