# Generated by Django 4.2.7 on 2025-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_colorsettings_faq_sitesettings_staticpage_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='admin_approved',
            field=models.BooleanField(default=False, verbose_name='موافقة الإدارة'),
        ),
    ]
